config/routes.rb
Rails.application.routes.draw do
  root to: 'members#index'

  resources :members 
  resources :teams 
  resources :projects do
    member do
      patch :add_to_project
      patch :remove_to_project
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :team
  has_many :members_projects, dependent: :destroy
  has_many :projects, through: :members_projects
  validates_presence_of :first_name, :last_name

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/members_project.rb
class MembersProject < ApplicationRecord
  belongs_to :member
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :members_projects, dependent: :destroy
  has_many :members, through: :members_projects
  validates_presence_of :name
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :members, dependent: :destroy
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :set_teams, only: [:new, :create, :edit, :update]

  def index
    @members = Member.all
  end

  def show
  end

  def new
    @member = Member.new
  end

  def edit
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to @member, notice: 'Member was successfully created.'
    else
      render :new
    end
  end

  def update
    if @member.update(member_params)
      redirect_to @member, notice: 'Member was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def set_teams
      @teams = Team.all
    end

    def member_params
      params.require(:member).permit(:first_name, :last_name, :city, :state, :country, :team_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_to_project, :remove_to_project]

  def index
    @projects = Project.all
  end

  def show
    @members = Member.all - Member.joins(:members_projects)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  def add_to_project
    @member = Member.find(params[:member_id])
    @project.members << @member
    redirect_to project_path(@project), notice: "#{@member.first_name} was successfully added to project."
  end

  def remove_to_project
    @member_project = @project.members_projects.find_by(member_id:  params[:member_id])
    @member_project.destroy
    redirect_to project_path(@project), notice: "#{@member_project.member.first_name} was successfully removed to project."
  end


  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  def index
    @teams = Team.all
  end

  def show
  end

  def new
    @team = Team.new
  end

  def edit
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to @team, notice: 'Team was successfully created.'
    else
      render :new
    end
  end

  def update
    if @team.update(team_params)
      redirect_to @team, notice: 'Team was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @team.destroy
    redirect_to teams_url, notice: 'Team was successfully destroyed.'
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamProjectTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
    
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: @member, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: 'form-control', placeholder: 'Enter first name', required: true %>
    </div>
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: 'form-control', placeholder: 'Enter last name', required: true %>
    </div>
    <div class="form-group">
      <%= form.label :city %>
      <%= form.text_field :city, class: 'form-control', placeholder: 'Enter city' %>
    </div>
    <div class="form-group">
      <%= form.label :state %>
      <%= form.text_field :state, class: 'form-control', placeholder: 'Enter state' %>
    </div>
    <div class="form-group">
      <%= form.label :country %>
      <%= form.text_field :country, class: 'form-control', placeholder: 'Enter country' %>
    </div>
    <div class="form-group">
      <%= form.label :team_id, "Team" %>
      <%= form.collection_select :team_id, Team.all, :id, :name, { prompt: "Select a team" }, { class: 'form-control' } %>
    </div>
   
    <div clsss="d-flex">
      <%= form.submit "Create Member", class: 'btn btn-primary mt-3' %>
      <%= link_to "Cancel", members_path, class: 'btn btn-secondary mt-3' %>
    </div>
  <% end %>

app/views/members/edit.html.erb
<div class="container">
  <h1>Edit Member</h1>
  <%= render 'form', action: 'Update'%>
</div>

app/views/members/index.html.erb
<div class="container">
  <h1>Members</h1>
  <table class="table">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>City</th>
        <th>State</th>
        <th>Country</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.first_name %></td>
          <td><%= member.last_name %></td>
          <td><%= member.city %></td>
          <td><%= member.state %></td>
          <td><%= member.country %></td>
          <td><%= link_to 'Show', member_path(member), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_member_path(member), class: 'btn btn-secondary' %></td>
          <td><%= button_to 'Destroy', member_path(member), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Member', new_member_path, class: 'btn btn-success' %>
</div>

app/views/members/new.html.erb
<div class="container">
  <h1>New Member</h1>
  <%= render 'form', action: 'Create'%>
</div>

app/views/members/show.html.erb
<div class="container">
  <h1><%= @member.full_name %></h1>
  <% if @member.projects.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Projects</th>
        </tr>
      </thead>
      <tbody>
        <% @member.projects.each do |project| %>
          <tr>
            <td><%= link_to project.name, project_path(project) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= link_to 'Edit', edit_member_path(@member), class: 'btn btn-secondary' %>
  <%= link_to 'Back', members_path, class: 'btn btn-primary' %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class='d-flex'>
    <%= form.submit 'Create', class: 'btn btn-primary mt-3' %>
    <%= link_to 'Back', projects_path, class: 'btn btn-secondary mt-3' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Edit Project</h1>
  <%= render 'form', action: 'Update' %>
</div>

app/views/projects/index.html.erb
<div class="container">
  <h1>Projects</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= link_to 'Show', project_path(project), class: 'btn btn-primary' %></td>
          <td><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-secondary' %></td>
          <td><%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'New Project', new_project_path, class: 'btn btn-success' %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h1>New Project</h1>
  <%= render 'form', action: 'Create' %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <h1><%= @project.name %></h1>
  <%= form_with(url: add_to_project_project_path(@project), method: :patch, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :member_id, "Member" %>
        <%= form.collection_select :member_id, @members, :id, :full_name, { prompt: "Select a member" }, { class: 'form-control' } %>
      </div>
      <%= form.submit 'Add to project', class: 'btn btn-primary my-3' %>
  <% end %>

  <% if @project.members.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Project Members</th>
          <th>Team</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @project.members.each do |member| %>
          <tr>
            <td><%= link_to member.full_name, member_path(member) %></td>
            <td><%= link_to member.team.name, team_path(member.team) %></td>
            <td>
              <%= button_to 'Remove from project', remove_to_project_project_path(id: params[:id], member_id: member.id), method: 'patch',class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-secondary' %>
  <%= link_to 'Back', projects_path, class: 'btn btn-primary' %>
</div>

app/views/shared/_flash_message.html.erb
<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-5">
  <a class="navbar-brand" href="/">TPR</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Teams", teams_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Members", members_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Projects", projects_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>